### ISSUE TITLE
Allow adding 1 standalone subscription multiple times in the same bundle

### ISSUE THREAD

**Issue by hieusharp** [killbill/killbill-admin-ui#289] opened 2022-01-19 07:40 UTC
1. Create a standalone subscription.
2. In the "Add standalone subscription" dropdown select the same subscription.

**Comment by tungleduyxyz** [comment] 2023-07-02 15:48
Hi @reshmabidikar ,
Can you help me to clarify this ticket? 
I'm not quite sure where to **Add standalone subscription**

**Comment by reshmabidikar** [comment] 2023-07-05 06:07
I gave it a try and here are the steps to reproduce it:

1. Upload the [monthly-standalone-no-trial](https://github.com/killbill/killbill-admin-ui/files/11954319/monthly-standalone-no-trial.zip) catalog
2. Create a new account
3. Create a new subscription to the `standard-monthly` plan
4.  In the subscription screen, click `Add Standalone subscription` (See screenshot below):

<img width="884" alt="image" src="https://github.com/killbill/killbill-admin-ui/assets/85998496/0014d8c6-af13-4565-b6bf-8a1a8cb5e6e6">

5. Select the  `standard-monthly` plan and click `Save` - The subscription is added successfully to the bundle. **Expected behavior:**  This should not be allowed since the bundle already includes the `standard-monthly` plan. @pierre, could you please confirm this? So, it should not be possible to add the same plan to the bundle but it should be possible to add a different standalone plan?

**Comment by pierre** [comment] 2023-07-05 06:29
Actually, this is supported: you can have multiple standalone subscriptions in the same bundle, regardless of their plan. A standalone product is simply a product that cannot have add-ons (we shouldn't allow to add add-ons in the same bundle. mixed with standalone subscriptions). See https://docs.killbill.io/latest/userguide_subscription.html#_product_categories

BTW Your usecase could be solved using quantity nowadays - not sure if Kaui supports it yet though (if not, let's create a ticket for the work). See https://github.com/killbill/killbill/issues/1651

**Comment by reshmabidikar** [comment] 2023-07-05 07:04
> Actually, this is supported:

Okay, in that case, can we close this ticket? This ticket seems to indicate that such a behavior should not be supported. 

> we shouldn't allow to add add-ons in the same bundle. mixed with standalone subscriptions

Kaui already handles this. So, when the `Add standalone subscription` button is clicked, only the standalone subscriptions are listed. @tungleduyxyz, could you please confirm this?

> not sure if Kaui supports it yet though (if not, let's create a ticket for the work)

Done, I've filed https://github.com/killbill/killbill-admin-ui/issues/363.

**Comment by tungleduyxyz** [comment] 2023-07-05 15:39
Hi @reshmabidikar 

> So, when the Add standalone subscription button is clicked, only the standalone subscriptions are listed
Yes, that's correct
I added a catalog with 2 plans,
![image](https://github.com/killbill/killbill-admin-ui/assets/80109474/bf0982ec-2afd-4ef3-b961-c6ce93f458fc)
And when I go to Add standalone subscription part, it only displays the Standalone 
![image](https://github.com/killbill/killbill-admin-ui/assets/80109474/9d5b408e-7eae-4faa-8cf0-cd75f49ef757)

**Closed** 2023-07-05 19:31 UTC
Labels: enhancement
